import { wx_gotoNewUrl } from '../../../utils/fn'
Page({
  data:{
    shopList:[
      {
        id:1,
        title:'校长店铺',
        goods:[
          {
            id:'10',
            name:'苹果',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'21',
            name:'柿子',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'12',
            name:'橙子',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'31',
            name:'汽水',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'35',
            name:'果汁',
            img:'../../../static/image/index/card.png',
          },
        ]
      },
      {
        id:2,
        title:'学生店铺',
        goods:[
          {
            id:'23',
            name:'土豆',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'32',
            name:'花生露',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'13',
            name:'李子',
            img:'../../../static/image/index/card.png',
          },
          {
            id:'31',
            name:'汽水',
            img:'../../../static/image/index/card.png',
          },
        ]
      },
    ]
  },
  // 点击店铺
  gotoShop(e){
    console.log(e.currentTarget.dataset.id)
    wx_gotoNewUrl('navigateTo','/pages/index/shops/index',{id:e.currentTarget.dataset.id,type:'shops'})
  },
  // 点击商品
  gotoGoods(e){
    console.log(e.currentTarget.dataset.item.id)
    wx_gotoNewUrl('navigateTo','/pages/index/shops/index',{id:e.currentTarget.dataset.item.id,type:'goods'})
  }
})